### ISSUE TITLE
USB connection teensy -> drone

### ISSUE THREAD

**Issue by newtonseple** [newtonseple/eit-pelican#4]
* [x] Prototype USB connection tested and working with teensy sending data.
* [x] Circuit board ordered
* [x] Get curcuit board (waiting for elprolab)
* [x] Test circuit board USB

**Comment by newtonseple** [comment]
![img_20180228_134246](https://user-images.githubusercontent.com/6238612/37086168-32fb3f58-21f7-11e8-9e7a-c41483c5cb9f.jpg)

**Comment by newtonseple** [comment]
Circuit board is in the works. Meanwhile, a prototype interface can be made from
* [ ] 1 TX24-30R-12ST-H1E (connector)
* [ ] 1 female USB-A or male USB-µB
* [ ] (leads)
* [ ] Solder according to figure

**Comment by Kneerk** [comment]
Circuitboard ordered 
![acc bay](https://user-images.githubusercontent.com/17024040/37394735-c1ff4ce4-2774-11e8-9ddb-6084b397ca50.png)

**Comment by newtonseple** [comment]
Curcuit board complete, only missing standoffs and a more permanent mounting solution

**Comment by Kneerk** [comment]
Mounting Complete
