### ISSUE TITLE
Audio connection: Barryvox -> Teensy

### ISSUE THREAD

**Issue by newtonseple** [newtonseple/eit-pelican#8]

**Comment by newtonseple** [comment]
Recommended ADC filter circuit:
![](https://www.pjrc.com/teensy/gui/img/adccircuit.png)

**Comment by Kneerk** [comment]
Circuitboard ordered

![acc bay](https://user-images.githubusercontent.com/17024040/37394637-8521e1c4-2774-11e8-82c7-01b57346e256.png)

**Comment by newtonseple** [comment]
Curcuit board complete, only missing standoffs and a more permanent mounting solution

**Comment by Kneerk** [comment]
Mounting Complete
