### ISSUE TITLE
Programmed flight interrupt test

### ISSUE THREAD

**Issue by KaHole** [newtonseple/eit-pelican#9]
Test that controller can override scripted flight.

Up-down test

1. Arm and lift off to 6 meters
2. Script: sleep for 30 seconds
3. Try controlling drone with remote controller
4. Script: initiate landing sequence / return to launch

What happens?
Do we get control of the drone?
Does the script stop completely, or will it concurrently run -> land after 30 seconds even though we interrupted with the remote ?

**Comment by stianmyd** [comment]
Tested flight with script on github "fly_pelican_v1.py"

1st fligth:
Successful, but interrupted by us because of unanticipated behavior from drone.

2nd flight:
Successful, fully autonomous flight. It seems that the RTL mode has a default altitude of 15m.
